In [1]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
stopwords=stopwords.words('english')

In [2]:
import string
import collections

In [3]:
data = pd.read_excel('ticketdata.xlsx')
data['corpus'] = data['reason'] +" "+ data['initial_description']

In [4]:
def remove_stopwords(sentence, stopwords):
	sentencewords = sentence.split()
	resultwords  = [word for word in sentencewords if word.lower() not in stopwords]
	result = ' '.join(resultwords)
	return result

In [5]:
REPLACE_NO_SPACE = re.compile("[^A-Za-z\s]")
stemmer = nltk.SnowballStemmer('english')
lemmatizer=nltk.WordNetLemmatizer()
def preprocess_reviews(data):
    data = [REPLACE_NO_SPACE.sub("", str(line).lower()) for line in data]
    data = [remove_stopwords(w,stopwords) for w in data]
    #data = [lemmatizer.lemmatize(w) for w in data]
    #data = [stemmer.stem(w) for w in data]
    return data

In [6]:
raw_input=preprocess_reviews(data['corpus'])

In [7]:
raw_input

['account creation request two new users virtusa team please create credentials two resources shubham sarogi helpdeskmonitoring team santosh lohar unixstorage team',
 'pacing report folders please access reading writing drive est thank michelle miura',
 'cant print desk moved last week tried print got printer responding message probably get assigned local printer well charles',
 'k indisign working k indisign working please find error screenshot id sukumar thanks subodh',
 'need enable lync account need enable lync account',
 'new employee two new users virtusa team new hire form submission date name subham saraogi dept helpdeskmonitoring team title office location wns offshore employee duration full time mirror ad account aditya pardeshi ad account name ssaraogi email address saraogialmcom domain almdomain ny udrive srvfilenyusersusername name santosh lohar dept helpdeskmonitoring team title unixstorage admin office location wns offshore employee duration full time mirror ad account s

In [8]:
my_words=[]
for line in raw_input:
    line=line.split(' ')
    for word in line:
        my_words.append(word)

In [9]:
filtered_words=[word for word in my_words if len(word)<13]

# Spell checker code starts from here

In [10]:
my_vocabulary=list(set(filtered_words))

In [11]:
# dictionary={ch: n for n, ch in enumerate(string.ascii_lowercase)}

In [12]:
# for k in dictionary:
#     dictionary[k]=dictionary[k]+1

In [13]:
# reverse_dictionary=dict(zip(dictionary.values(), dictionary.keys()))

In [14]:
keypad='qwertyuioplkjhgfdsazxcvbnm'

In [15]:
reverse_dictionary={}
j=0
for letter in keypad:
    reverse_dictionary[j+1]=letter
    j=j+1    

In [16]:
dictionary=dict(zip(reverse_dictionary.values(), reverse_dictionary.keys()))

In [17]:
counter=collections.Counter(filtered_words)

In [18]:
counter.most_common(3000)

[('please', 1185),
 ('access', 1024),
 ('request', 1004),
 ('new', 928),
 ('hi', 814),
 ('employee', 665),
 ('need', 523),
 ('team', 499),
 ('email', 470),
 ('adbase', 470),
 ('alm', 460),
 ('user', 436),
 ('help', 412),
 ('subject', 399),
 ('sent', 397),
 ('account', 389),
 ('thanks', 352),
 ('issue', 329),
 ('date', 327),
 ('work', 323),
 ('desk', 321),
 ('vpn', 318),
 ('citrix', 312),
 ('ad', 298),
 ('outlook', 296),
 ('broadway', 292),
 ('ny', 277),
 ('server', 270),
 ('name', 266),
 ('cc', 260),
 ('error', 256),
 ('location', 245),
 ('software', 245),
 ('york', 244),
 ('pc', 244),
 ('position', 244),
 ('folder', 241),
 ('pm', 236),
 ('th', 228),
 ('floor', 225),
 ('working', 224),
 ('set', 218),
 ('yes', 218),
 ('needs', 216),
 ('k', 214),
 ('october', 209),
 ('manager', 201),
 ('laptop', 201),
 ('contact', 196),
 ('phone', 194),
 ('office', 193),
 ('drive', 192),
 ('thank', 190),
 ('tech', 189),
 ('regards', 184),
 ('kindly', 183),
 ('get', 174),
 ('able', 174),
 ('business', 166

In [33]:
counter.get('hal')

2

In [19]:
better_vocabulary=[]
for word in my_vocabulary:
    if(counter.get(word)>1):
        better_vocabulary.append(word)

In [20]:
def vectorizer(list_of_words):
    vects=[]
    for word in list_of_words:
        vector=[0]*12
        j=0
        for alphabet in word:
            vector[j]=dictionary[alphabet]
            j=j+1
        vector[0]=vector[0]*10
        vects.append(vector)
    return vects

In [21]:
vects=vectorizer(better_vocabulary)

In [22]:
from sklearn.neighbors import NearestNeighbors
kn = NearestNeighbors(n_neighbors=5, radius=1.0, algorithm='auto', 
                      leaf_size=30, metric='minkowski', p=2, metric_params=None, n_jobs=-1)

In [23]:
kn.fit(vects)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=-1, n_neighbors=5, p=2, radius=1.0)

In [24]:
text=vectorizer(['helo'])
t=kn.kneighbors(text,5,return_distance=True)

In [25]:
t

(array([[1.        , 6.40312424, 7.        , 8.1240384 , 8.54400375]]),
 array([[3361,   76,  237,  408, 2877]], dtype=int64))

In [26]:
t[0]

array([[1.        , 6.40312424, 7.        , 8.1240384 , 8.54400375]])

In [27]:
t[0][0][0]

1.0

In [28]:
for i in t[1][0]:
    print(better_vocabulary[i])

help
http
hook
high
hope
